[package]
name = "bilistream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["cookies","json"] }
reqwest-middleware = "0.1.6"
reqwest-retry = "0.1.5"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.137",features = ["derive"] }
serde_json = "1.0.81"
serde_yaml = "0.8"
execute = "0.2.11"
tracing = "0.1.35"
tracing-subscriber = "0.2.0"
async-trait = "0.1.56"
urlencoding = "2.1.0"
m3u8-rs = "4.0.0"
rand = "0.8.5"
regex = "1.5.6"